# Generated by Django 3.0.5 on 2023-11-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_auto_20231113_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherextra',
            name='salary',
        ),
    ]
