# Generated by Django 3.0.5 on 2023-11-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_teacherextra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('by', models.CharField(default='school', max_length=20, null=True)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
