# Generated by Django 3.0.5 on 2023-11-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentextra',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='studentextra',
            name='roll',
        ),
    ]
